/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mv;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // @Test public void testAppHasAVirtualMachine() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a virtual machine instantiated.", classUnderTest.getVM());
    // }

    @Test public void testIsWordEmpty() {
        Word emptyWordUnderTest = new Word(Opcode.___, -1, -1, -1);
        assertTrue("Word has no content.", Word.isEmpty(emptyWordUnderTest));
    }
}
