/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mv;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // @Test public void testAppHasAVirtualMachine() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a virtual machine instantiated.", classUnderTest.getVM());
    // }
}
