/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mv;

public class App {

    public static void main(String[] args) {
        VM vm = new VM();
		vm.test1();
    }
    
}
