/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mv;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    public static VM vm;

    public static void main(String[] args) {    log.info("It works!\n");
        
        Programa[] programas = {
            Programas.p0,
            Programas.p1,
            Programas.p2,
            Programas.p3,
            Programas.p4,
        };
        
        vm = new VM();                          log.info("{} (Setup) All set!\n", VM.mark);

        vm.init(programas);

    }

    /* END */

    private static Logger log = LoggerFactory.getLogger(CPU.class);
}
