/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mv;

public class App {

    public static VM vm;

    public static void main(String[] args) {

        vm = new VM();

        // vm.p1();
        // vm.p2();
        vm.p3();
        // vm.p4();
    }

    public static VM getVM() {
        return vm;
    }
    
}
